VERSION="0.0.1"
PROPOSAL_NAME="Test Proposal"
PROPOSAL_DESCRIPTION="The description of this proposal"
PROPOSAL_CONTACT_EMAIL="hi@testdao.org"
PROPOSAL_DISCUSSION_LINK="https://testdao.org"
PROPOSAL_VOTING_TOKEN="GOV:GBNOMH3B6BIQE65TZVVBNOCTMLN7MYORU5GX6YNBX5YBGCI45R2EMGOV"
PROPOSAL_DURATION_SECONDS="3000"
QUORUM_STATIC="40000"
[[PROPOSAL_VOTING_OPTIONS]]
label="one"
value="vote for one"
xdr="AAAAAgAAAAAzmy8imtejMIgSbMMXk9hGT0JwJAYgqSa6qUHsfvTOAwAAAGQAFDXMAAAAAQAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAQAAAABjI7vSXjmgz0+a3XZS/qPXSjVpkiTnnDovaOi12CdJ2AAAAAAAAAAABfXhAAAAAAAAAAAA"
[[PROPOSAL_VOTING_OPTIONS]]
label="two"
value="vote for two"
xdr="AAAAAgAAAAAzmy8imtejMIgSbMMXk9hGT0JwJAYgqSa6qUHsfvTOAwAAAGQAFDXMAAAAAQAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAQAAAABjI7vSXjmgz0+a3XZS/qPXSjVpkiTnnDovaOi12CdJ2AAAAAAAAAAAC+vCAAAAAAAAAAAA"